# Generated by Django 5.0.3 on 2024-03-22 13:44

import django.core.validators
import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="seller",
            fields=[
                ("seller_name", models.CharField(default="", max_length=200)),
                (
                    "seller_id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="seller ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        validators=[product.models.validate_mail],
                    ),
                ),
                ("phone", models.PositiveBigIntegerField(blank=True)),
                ("address", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_name", models.CharField(blank=True, max_length=255)),
                (
                    "product_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "product_image",
                    models.ImageField(blank=True, default="", upload_to=""),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=1000000,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("available_stock", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="product.category",
                    ),
                ),
                (
                    "seller_id",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="product.seller",
                    ),
                ),
            ],
        ),
    ]
